repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
        # Ignoring unused imports within __init__.py files.
        args: [ --per-file-ignores, '*__init__.py:F401', --fix ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.3.0"
    hooks:
    -   id: pydocstyle
        args: ["--convention=google"]
        files: mojo|examples
