name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
# TODO: Enable once documentation added
#      - uses: pre-commit/action@v3.0.1
#        with:
#          extra_args: --all-files
      - name: Tests
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev libxinerama-dev libxcursor-dev libxrandr-dev libxi-dev
          pip install ".[dev]"
          pytest tests/
